### PR TITLE
Added Input

### PR DESCRIPTION
**Pull request by dubeyaditya29**
Added two inputs (text and password)

https://user-images.githubusercontent.com/48158220/153814827-e02fd3d7-8744-4253-9458-73cad72aa491.mp4

### CODE REVIEW

**Review by bhanuprakashj — COMMENTED** [review]
code looks good to me!!
but I have small query here while using the component library, if in the same page user wants to add to multiple seePassword fields is it feasible?

**Comment by dubeyaditya29** [comment]
@bhanuprakashj  no its not can you suggest how can I implement this.

**Comment by bhanuprakashj** [comment]
> @bhanuprakashj no its not can you suggest how can I implement this.

Instead of adding event listener to seePassword id, you can try adding click event listener to body/window and on clicking get the target which it is clicked on with it's closest parent you are looking for and perform desired action now. Make sure to perform the desired action only when it is clicked on the element you are looking for.
Reference: [Event delegation](https://javascript.info/event-delegation)

**Comment by dubeyaditya29** [comment]
@bhanuprakashj  Thanks for the suggestion I have used the concept of event delegation.Now the code can handle multiple seePassword fields.

**Review by dev-enforced — APPROVED** [review]
The code looks good to me!! Good work on the password suggestion given by @bhanuprakashj !!
Keep the name of the variables different from the keywords to avoid confusion later!!

**Pull request merged**
